#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace Ani_NewLevelSequence_Up { class USequenceDirector_C; }

namespace KuroSceneInteraction_14 { class ATPrefab_SM_Gat_14A_C; }

namespace KuroSceneInteraction_40 { class ATPrefab_SM_ExplosiveRock_C; }

namespace KuroSceneInteraction_6 { class ATPrefab_SM_Gat_19A_C; }

namespace KuroSceneInteraction_3 { class ATPrefab_SM_Gat_18A_C; }

namespace KuroSceneInteraction_33 { class ATPrefab_SM_Gat_19A_C; }

namespace KuroSceneInteraction_35 { class ATPrefab_SM_Gat_30A_C; }

namespace TPrefab_SM_Pro_Tow_03A { class ATPrefab_SM_Pro_Tow_03A_C; }

namespace TPrefab_SM_ExplosiveRock { class ATPrefab_SM_ExplosiveRock_C; }

namespace Seq_Dajijiguan02_Init { class USequenceDirector_C; }

namespace TPrefab_SM_Gat_14A { class ATPrefab_SM_Gat_14A_C; }

namespace KuroSceneInteraction_18 { class ATPrefab_SM_Gat_14A_C; }

namespace KuroSceneInteraction_19 { class ATPrefab_SM_Gat_19A_C; }

namespace SC_Anke_Burst01 { class USequenceDirector_C; }

namespace Ani_MissionPnlProcess_StartWithChild { class USequenceDirector_C; }

namespace TPrefab_SM_DungeonDoor_Base { class ATPrefab_SM_DungeonDoor_Base_C; }

namespace KuroSceneInteraction_17 { class ATPrefab_SM_Gat_19A_C; }

namespace KuroSceneInteraction_10 { class ATPrefab_SM_Gat_17A_C; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace TPrefab_SM_Gat_18A { class ATPrefab_SM_Gat_18A_C; }

namespace KuroSceneInteraction_31 { class ATPrefab_SM_DungeonDoor_Base_C; }

namespace KuroSceneInteraction_55 { class ATPrefab_SM_Pro_HuanXiangBox_02_CBT3_C; }

namespace TPrefab_SM_Gat_13A { class ATPrefab_SM_Gat_13A_C; }

namespace SC_Bailian_Burst01 { class USequenceDirector_C; }

namespace KuroSceneInteraction_34 { class ATPrefab_SM_Gat_18A_C; }

namespace TPrefab_SM_Pro_Gravity_Base { class ATPrefab_SM_Pro_Gravity_Base_C; }

namespace TPrefab_SM_Gat_17A { class ATPrefab_SM_Gat_17A_C; }

namespace KuroSceneInteraction_47 { class ATPrefab_SM_MingJing_C; }

namespace KuroSceneInteraction_2 { class ATPrefab_SM_Gat_18A_C; }

namespace KuroSceneInteraction_38 { class ATPrefab_SM_Pro_Box_02_CBT3_C; }

namespace KuroSceneInteraction_13 { class ATPrefab_SM_Gat_17A_C; }

namespace TPrefab_SM_Pro_HuanXiangBox_03_CBT3 { class ATPrefab_SM_Pro_HuanXiangBox_03_CBT3_C; }

namespace KuroSceneInteraction_42 { class ATPrefab_SM_Pro_Gravity_Base_C; }

namespace TPrefab_SM_Pro_Box_08 { class ATPrefab_SM_Pro_Box_08_C; }

namespace TPrefab_SM_WYQ_Shengxian { class ATPrefab_SM_WYQ_Shengxian_C; }

namespace KuroSceneInteraction_48 { class ATPrefab_SM_Pro_HuanXiangBox_03_CBT3_C; }

namespace KuroSceneInteraction_5 { class ATPrefab_SM_Gat_19A_C; }

namespace TPrefab_SM_Pro_HuanXiangBox_02_CBT3 { class ATPrefab_SM_Pro_HuanXiangBox_02_CBT3_C; }

namespace KuroSceneInteraction_49 { class ATPrefab_SM_Pro_Box_02_CBT3_C; }

namespace GA_ChangeCharacterAttack_0 { class UGA_ChangeCharacterAttack_C; }

namespace TPrefab_SM_ExplosiveRock_Base { class ATPrefab_SM_ExplosiveRock_Base_C; }

namespace KuroSceneInteraction_28 { class ATPrefab_SM_Gat_18A_C; }

namespace TPrefab_SM_Pro_Box_02_CBT3 { class ATPrefab_SM_Pro_Box_02_CBT3_C; }

namespace Seq_Dajijiguan02_End { class USequenceDirector_C; }

namespace TPrefab_SM_Gat_30A { class ATPrefab_SM_Gat_30A_C; }

namespace TPrefab_SM_MingJing_set { class ATPrefab_SM_MingJing_set_C; }

namespace GA_ChangeCharacterAttack { class UGA_ChangeCharacterAttack_C; }

namespace KuroSceneInteraction_4 { class ATPrefab_SM_Gat_17A_C; }

namespace TPrefab_SM_Pro_Tow_02A { class ATPrefab_SM_Pro_Tow_02A_C; }

namespace KuroSceneInteraction_26 { class ATPrefab_SM_Gat_14A_C; }

namespace KuroSceneInteraction_8 { class ATPrefab_SM_Pro_Box_08_C; }

namespace TPrefab_SM_Gat_19A { class ATPrefab_SM_Gat_19A_C; }

namespace KuroSceneInteraction_27 { class ATPrefab_SM_Gat_18A_C; }

namespace KuroSceneInteraction_21 { class ATPrefab_SM_Gat_14A_C; }

namespace KuroSceneInteraction_29 { class ATPrefab_SM_Gat_13A_C; }

namespace TPrefab_SM_MingJing { class ATPrefab_SM_MingJing_C; }

namespace KuroSceneInteraction_65 { class ATPrefab_SM_WYQ_Middle_Shengxian_C; }

namespace KuroSceneInteraction_20 { class ATPrefab_SM_Pro_Tow_03A_C; }

namespace KuroSceneInteraction_46 { class ATPrefab_SM_MingJing_set_C; }

namespace Ani_MissionPnlProcess_Start { class USequenceDirector_C; }

namespace TPrefab_SM_WYQ_Middle_Shengxian { class ATPrefab_SM_WYQ_Middle_Shengxian_C; }

namespace KuroSceneInteraction_1 { class ATPrefab_SM_Gat_18A_C; }

namespace Seq_Dajijiguan02_Start { class USequenceDirector_C; }

namespace KuroSceneInteraction_12 { class ATPrefab_SM_Gat_17A_C; }

namespace KuroSceneInteraction_22 { class ATPrefab_SM_Gat_13A_C; }

namespace KuroSceneInteraction_23 { class ATPrefab_SM_Gat_13A_C; }

namespace KuroSceneInteraction_24 { class ATPrefab_SM_Gat_13A_C; }

namespace KuroSceneInteraction_25 { class ATPrefab_SM_Gat_17A_C; }

namespace KuroSceneInteraction_30 { class ATPrefab_SM_Gat_19A_C; }

namespace KuroSceneInteraction_32 { class ATPrefab_SM_Gat_19A_C; }

namespace KuroSceneInteraction_36 { class ATPrefab_SM_Pro_HuanXiangBox_02_CBT3_C; }

namespace KuroSceneInteraction_39 { class ATPrefab_SM_ExplosiveRock_Base_C; }

namespace KuroSceneInteraction_50 { class ATPrefab_SM_Pro_Tow_03A_C; }

namespace KuroSceneInteraction_51 { class ATPrefab_SM_Pro_Box_02_CBT3_C; }

namespace KuroSceneInteraction_60 { class ATPrefab_SM_Pro_Tow_02A_C; }

namespace KuroSceneInteraction_62 { class ATPrefab_SM_WYQ_Shengxian_C; }

namespace KuroSceneInteraction_63 { class ATPrefab_SM_Pro_Tow_02A_C; }

namespace KuroSceneInteraction_64 { class ATPrefab_SM_WYQ_Middle_Shengxian_C; }

