#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DeveloperSettings

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class DeveloperSettings.DeveloperSettings
// 0x0018 (0x0048 - 0x0030)
class UDeveloperSettings : public UObject
{
public:
	uint8                                         Pad_14E0[0x18];                                    // 0x0030(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DeveloperSettings">();
	}
	static class UDeveloperSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDeveloperSettings>();
	}
};
static_assert(alignof(UDeveloperSettings) == 0x000008, "Wrong alignment on UDeveloperSettings");
static_assert(sizeof(UDeveloperSettings) == 0x000048, "Wrong size on UDeveloperSettings");

}

